version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        VARIANT: "3.10"
        NODE_VERSION: "14"

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    network_mode: service:postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres: null
