# Generated by Django 4.0.4 on 2022-05-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_index=True, max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('complemento', models.CharField(max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=45)),
                ('nome_fantasia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'escola',
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('regiao', models.CharField(max_length=45)),
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
            ],
            options={
                'db_table': 'estilo',
            },
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('email', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'federacao',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_relacao', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('avo', 'Avô'), ('avo_mae', 'Avó'), ('outros', 'Outros')], max_length=50)),
                ('rg', models.CharField(db_index=True, max_length=20)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('email', models.CharField(max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'responsavel_atletas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rg', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
                ('orgao_emissor', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('facebook', models.CharField(max_length=45, null=True)),
                ('telefone', models.CharField(max_length=45, null=True)),
                ('celular', models.CharField(max_length=45)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.federacao')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField()),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.federacao')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.professor')),
            ],
            options={
                'db_table': 'presidente',
            },
        ),
        migrations.CreateModel(
            name='EstiloRelacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(max_length=45)),
                ('origem_object_id', models.IntegerField()),
                ('estilos_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.estilo')),
                ('origem_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'estilo_relacoes',
            },
        ),
        migrations.CreateModel(
            name='EscolaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.BooleanField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.professor')),
            ],
            options={
                'db_table': 'escola_professor',
            },
        ),
        migrations.AddField(
            model_name='escola',
            name='federacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.federacao'),
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(db_index=True, max_length=20, null=True)),
                ('cpf', models.CharField(db_index=True, max_length=11, null=True)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], db_index=True, max_length=1)),
                ('email', models.CharField(max_length=255, null=True)),
                ('data_nascimento', models.DateField()),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federacao')),
                ('responsavel_atleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.responsavelatleta')),
            ],
            options={
                'db_table': 'atletas',
            },
        ),
    ]
