# Generated by Django 4.0.4 on 2022-05-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_index=True, max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('complemento', models.CharField(max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('email', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'federacoes',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_relacao', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('avo', 'Avô'), ('avo_mae', 'Avó'), ('outros', 'Outros')], max_length=50)),
                ('rg', models.CharField(db_index=True, max_length=20)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('email', models.CharField(max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'responsavel_atletas',
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(db_index=True, max_length=20, null=True)),
                ('cpf', models.CharField(db_index=True, max_length=11, null=True)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], db_index=True, max_length=1)),
                ('email', models.CharField(max_length=255, null=True)),
                ('data_nascimento', models.DateField()),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federacao')),
                ('responsavel_atleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.responsavelatleta')),
            ],
            options={
                'db_table': 'atletas',
            },
        ),
    ]
