# Generated by Django 4.0.4 on 2022-05-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='federacao',
            table='escola',
        ),
    ]
