# Generated by Django 4.0.4 on 2022-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='codigo',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
