# Generated by Django 4.0.4 on 2022-05-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_atleta_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('federacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federacao')),
            ],
            options={
                'db_table': 'escolas',
            },
        ),
    ]
